version: 2.1

orbs:
  npm: lifeway/npm-tools@0.0.6

common:
  run-on-pr: &run-on-pr
    filters:
      branches:
        ignore: master

workflows:
  pr-checks:
    jobs:
      - npm/install:
          <<: *run-on-pr
      - npm/run-script:
          <<: *run-on-pr
          name: audit
          script: audit
          requires:
            - npm/install
      - npm/run-script:
          <<: *run-on-pr
          name: test
          script: test:ci
          requires:
            - npm/install
      - npm/run-script:
          <<: *run-on-pr
          name: lint
          script: lint
          requires:
            - npm/install
