version: 2.1

orbs:
  npm: lifeway/npm-tools@0.0.6
  puppeteer: threetreeslight/puppeteer@0.1.2

executors:
  node:
    docker:
      - image: circleci/node:12
  cypress:
    docker:
      - image: cypress/base:12

common:
  run-on-pr: &run-on-pr
    filters:
      branches:
        ignore: master
  run-on-master: &run-on-master
    filters:
      branches:
        only: master
  context: &team-context rundmg
  setup: &setup
    executor: node
    context: *team-context


jobs:
  check-changelog:
    executor: node
    steps:
      - checkout
      - run:
          name: ensure changelog has been modified
          command: |
            ! git diff -s --exit-code upstream/master -- CHANGELOG.md

  install:
    executor: node
    environment:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - npm/npm-install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths:
            - ./

  client-test:
    executor: cypress
    steps:
      - attach_workspace:
          at: ./
      - restore_cache:
          key: cypress-binary-cache-{{ checksum "package-lock.json" }}
      - run:
          name: verify cypress binary is installed
          command: |
            if ! npx cypress verify; then
              npx cypress install
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/Cypress
      - npm/npm-run-script:
          script: test:ci
      - store_artifacts:
          path: ./reports/tests
          destination: tests
      - store_artifacts:
          path: ./reports/coverage
          destination: coverage
      - store_test_results:
          path: ./reports/tests

  visual-test:
    docker:
      - image: circleci/node:12
        environment:
          NODE_ENV: development
    steps:
      - checkout
      - puppeteer/install
      - npm/npm-run-script:
          script: test:visual
      - store_artifacts:
          path: ./reports/visual
          destination: visual
      - store_test_results:
          path: ./reports/visual

  publish:
    executor: node
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: check if version exists
          command: |
            if npm run version:check; then
              echo "Current version has not been published yet, proceeding"
            else
              exit_message="Current version has already been published."
              echo "echo '${exit_message}'" >> $BASH_ENV
              echo "exit 0;" >> $BASH_ENV

              source $BASH_ENV
            fi
      - run:
          name: npm/publish
          command: |
            npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
            npm publish

workflows:
  check-and-release:
    jobs:
      - npm/install:
          <<: *setup
      - npm/run-script:
          <<: *setup
          name: audit
          script: audit
          requires:
            - npm/install
      - client-test:
          context: *team-context
          requires:
            - npm/install
      - visual-test:
          context: *team-context
          requires:
            - npm/install
      - npm/run-script:
          <<: *setup
          name: lint
          script: lint
          requires:
            - npm/install
      - npm/run-script:
          <<: *run-on-pr
          <<: *setup
          name: check-build
          script: build:check
          requires:
            - npm/install
      - check-changelog:
          <<: *run-on-pr
          context: *team-context
      - publish:
          <<: *run-on-master
          context: *team-context
          requires:
            - audit
            - client-test
            - visual-test
            - lint
